FROM php:8.4-fpm

ARG USER
ARG USER_ID
ARG GROUP_ID

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libicu-dev \
    zip \
    unzip \
    git \
    curl

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN curl -sL https://deb.nodesource.com/setup_22.x | bash \
    && apt-get install nodejs -y

RUN docker-php-ext-configure intl
RUN docker-php-ext-install pdo pdo_mysql intl opcache

WORKDIR /var/www

COPY . .

RUN groupadd --force -g $GROUP_ID $USER
RUN useradd -ms /bin/bash --no-user-group -g $GROUP_ID -u 1337 $USER
RUN usermod -u $USER_ID $USER

USER $USER
